# Generated by Django 5.2.13 on 2026-05-05 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_assinaturaconfiguracao_ativo'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE cadastros_configuracaosistema '
                        'DROP COLUMN IF EXISTS prazo_justificativa_dias, '
                        'DROP COLUMN IF EXISTS pt_ano, '
                        'DROP COLUMN IF EXISTS pt_ultimo_numero'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='configuracaosistema',
                    name='prazo_justificativa_dias',
                ),
                migrations.RemoveField(
                    model_name='configuracaosistema',
                    name='pt_ano',
                ),
                migrations.RemoveField(
                    model_name='configuracaosistema',
                    name='pt_ultimo_numero',
                ),
            ],
        ),
    ]
