# Generated by Django 5.2.13 on 2026-05-05 00:20

from django.db import migrations, models


def remover_assinaturas_extras(apps, schema_editor):
    assinatura_configuracao = apps.get_model('cadastros', 'AssinaturaConfiguracao')
    assinatura_configuracao.objects.exclude(
        tipo__in=['OFICIO', 'JUSTIFICATIVA', 'PLANO_TRABALHO', 'ORDEM_SERVICO'],
        ordem=1,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_remove_configuracao_prazo_pt_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaosistema',
            name='cargo_chefia',
        ),
        migrations.RemoveField(
            model_name='configuracaosistema',
            name='coordenador_adm_plano_trabalho',
        ),
        migrations.RemoveField(
            model_name='configuracaosistema',
            name='nome_chefia',
        ),
        migrations.RemoveField(
            model_name='configuracaosistema',
            name='nome_orgao',
        ),
        migrations.RemoveField(
            model_name='configuracaosistema',
            name='sede',
        ),
        migrations.RemoveField(
            model_name='configuracaosistema',
            name='sigla_orgao',
        ),
        migrations.AlterField(
            model_name='assinaturaconfiguracao',
            name='tipo',
            field=models.CharField(choices=[('OFICIO', 'Ofício'), ('JUSTIFICATIVA', 'Justificativa'), ('PLANO_TRABALHO', 'Plano de Trabalho'), ('ORDEM_SERVICO', 'Ordem de Serviço')], max_length=30),
        ),
        migrations.RunPython(remover_assinaturas_extras, migrations.RunPython.noop),
    ]
